Examen_dos/FrontEnd/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;

namespace FrontEnd.Models
{
    public partial class CustomerViewModel
    {

        public int CustomerId { get; set; }
        /// <summary>
        /// Foreign key to Person.BusinessEntityID
        /// </summary>
        public int? PersonId { get; set; }
        /// <summary>
        /// Foreign key to Store.BusinessEntityID
        /// </summary>
        public int? StoreId { get; set; }
        /// <summary>
        /// ID of the territory in which the customer is located. Foreign key to SalesTerritory.SalesTerritoryID.
        /// </summary>
        public int? TerritoryId { get; set; }
        /// <summary>
        /// Unique number identifying the customer assigned by the accounting system.
        /// </summary>
        public string AccountNumber { get; set; } = null!;
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; }
    }
}

Examen_dos/FrontEnd/Models/ErrorViewModel.cs
namespace FrontEnd.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen_dos/FrontEnd/Controllers/CustomerController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class CustomerController : Controller
    {
        CustomerHelper customerHelper= new CustomerHelper();


        // GET: EmpleadoController
        public ActionResult Index()
        {
            List<CustomerViewModel> lista = customerHelper.GetAll();
            return View(lista); ;
        }

        // GET: EmpleadoController/Details/5
        public ActionResult Details(int id)
        {
            CustomerViewModel customer = customerHelper.Get(id);

            return View(customer);
        }

        // GET: EmpleadoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmpleadoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerViewModel customer)
        {
            try
            {
                customer = customerHelper.Create(customer);
                return RedirectToAction("Details", new { id = customer.CustomerId });
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpleadoController/Edit/5
        public ActionResult Edit(int id)
        {
            CustomerViewModel customer = customerHelper.Get(id);

            return View(customer);
        }

        // POST: EmpleadoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerViewModel customer)
        {
            try
            {
                customer = customerHelper.Edit(customer);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpleadoController/Delete/5
        public ActionResult Delete(int id)
        {
            CustomerViewModel customer = customerHelper.Get(id);

            return View(customer);
        }

        // POST: EmpleadoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CustomerViewModel customer)
        {
            try
            {
                customerHelper.Delete(customer.CustomerId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();

            }
        }
    }
}

Examen_dos/FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen_dos/FrontEnd/Views/Customer/Create.cshtml
@model FrontEnd.Models.CustomerViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CustomerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <input asp-for="StoreId" class="form-control" />
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TerritoryId" class="control-label"></label>
                <input asp-for="TerritoryId" class="form-control" />
                <span asp-validation-for="TerritoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rowguid" class="control-label"></label>
                <input asp-for="Rowguid" class="form-control" />
                <span asp-validation-for="Rowguid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen_dos/FrontEnd/Views/Customer/Delete.cshtml
@model FrontEnd.Models.CustomerViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TerritoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TerritoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rowguid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rowguid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.HiddenFor(Model=>Model.CustomerId)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Examen_dos/FrontEnd/Views/Customer/Details.cshtml
@model FrontEnd.Models.CustomerViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CustomerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TerritoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TerritoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rowguid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rowguid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.CustomerId }) |
    <a asp-action="Index">Back to List</a>
</div>

Examen_dos/FrontEnd/Views/Customer/Edit.cshtml
@model FrontEnd.Models.CustomerViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CustomerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.HiddenFor(Model=>Model.CustomerId)
            
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <input asp-for="StoreId" class="form-control" />
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TerritoryId" class="control-label"></label>
                <input asp-for="TerritoryId" class="form-control" />
                <span asp-validation-for="TerritoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rowguid" class="control-label"></label>
                <input asp-for="Rowguid" class="form-control" />
                <span asp-validation-for="Rowguid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen_dos/FrontEnd/Views/Customer/Index.cshtml
@model IEnumerable<FrontEnd.Models.CustomerViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TerritoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rowguid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StoreId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TerritoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccountNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rowguid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.CustomerId  }) |
                    @Html.ActionLink("Details", "Details", new { id=item.CustomerId }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.CustomerId })
                </td>
            </tr>
        }
    </tbody>
</table>

Examen_dos/FrontEnd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examen_dos/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>